let promise  =  new promise((reject,resolev)=>{
    try{
        let success  =  Math.random>0.5
        if (success) {
            resole
            
        }
    }
    catch((error)=>{
        console.log(error)
    })
})