let promise  =  new Promise((reject,resolve)=>{
    
        set
)
promise.then((mess)=>
console.log(mess))
.catch((error)=>{
    console.log(error)
})
